//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodestruct.Steel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodestruct.Steel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteelFraming,0.01
        ///PaperOffice,0.02
        ///.
        /// </summary>
        internal static string AISC_DG11_ModalDamping {
            get {
                return ResourceManager.GetString("AISC_DG11_ModalDamping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OccupancyId&gt;&lt;P_o&gt;&lt;AccelerationLimit&gt;
        ///Office,65,0.005
        ///Residence,65,0.005
        ///Chirch,65,0.005
        ///Shopping mall,65,0.015
        ///FootBridgeIndoor,92,0.05
        ///FootBridgeOutdoor,92,0.05
        ///.
        /// </summary>
        internal static string AISC_DG11_VibrationLimits {
            get {
                return ResourceManager.GetString("AISC_DG11_VibrationLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A36,36,58,0,10
        ///A36_32ksi,32,58,0,10
        ///A53GradeB,35,60
        ///A500GradeB_42ksi,42,58
        ///A500GradeB_46ksi,46,58
        ///A500GradeC_46ksi,46,62
        ///A500GradeC_50ksi,50,62
        ///A501,36,58
        ///A529Grade50,50,65
        ///A529Grade55,55,75
        ///A572Grade42,42,60
        ///A572Grade50,50,65
        ///A572Grade55,55,70
        ///A572Grade60,60,75
        ///A572Grade65,65,80
        ///A618GradeIandII,50,70
        ///A618GradeIII,50,65
        ///A913_50ksi,50,60
        ///A913_60ksi,60,75
        ///A913_65ksi,65,80
        ///A913_70ksi,70,90
        ///A992,50,65
        ///A242_42ksi,42,63
        ///A242_46ksi,46,67
        ///A242_50ksi,50,70
        ///A588,50,70
        ///A847,50,70
        ///A36_32ksi,3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AISC360_10_MaterialProperties {
            get {
                return ResourceManager.GetString("AISC360_10_MaterialProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Diameter&gt;&lt;Standard&gt;&lt; Oversize&gt;&lt;Short-Slot Width&gt;&lt;Short-Slot Length&gt;&lt;Long-Slot Width&gt;&lt;Long-Slot Length&gt;
        ///0.5,0.5625,0.625,0.5625,0.6875,0.5625,1.25
        ///0.625,0.6875,0.8125,0.6875,0.875,0.6875,1.5625
        ///0.75,0.8125,0.9375,0.8125,1,0.8125,1.875
        ///0.875,0.9375,0.6875,0.9375,1.125,0.9375,2.1875
        ///1,1.0625,1.25,1.0625,1.3125,1.0625,2.5.
        /// </summary>
        internal static string AISC360_10TableJ3_3NominalHoleDimensions {
            get {
                return ResourceManager.GetString("AISC360_10TableJ3_3NominalHoleDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Bolt diameter&gt; &lt;Edge distance&gt;
        ///0.5,0.75
        ///0.625,0.875
        ///0.75,1
        ///0.875,1.125
        ///1,1.25
        ///1.125,1.5
        ///1.25,1.625.
        /// </summary>
        internal static string AISC360_10TableJ3_4_MinimumEdgeDistance {
            get {
                return ResourceManager.GetString("AISC360_10TableJ3_4_MinimumEdgeDistance", resourceCulture);
            }
        }
    }
}
