//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodestruct.Wood.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodestruct.Wood.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALASKA CEDAR,SelectStructural,2 in. &amp; wider,1150,625,165,525,1000,1400000,510000,0.47
        ///ALASKA CEDAR,No.1,2 in. &amp; wider,975,525,165,525,900,1300000,470000,0.47
        ///ALASKA CEDAR,No.2,2 in. &amp; wider,800,425,165,525,750,1200000,440000,0.47
        ///ALASKA CEDAR,No.3,2 in. &amp; wider,450,250,165,525,425,1100000,400000,0.47
        ///ALASKA CEDAR,Stud,2 in. &amp; wider,625,350,165,525,475,1100000,400000,0.47
        ///ALASKA CEDAR,Construction,2 in. - 4 in. wide,900,500,165,525,950,1200000,440000,0.47
        ///ALASKA CEDAR,Standard,2 in. - 4 in. wide,500,27 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Suppl_Table4A {
            get {
                return ResourceManager.GetString("NDS2015_Suppl_Table4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;&gt;  &lt;&gt;  &lt;&gt;  l_u/d &lt; 7   &lt;&gt;  &lt;7&lt;=l_u/d &lt;=14.3 &gt; &lt;&gt;  &lt;l_u/d &gt;14.3&gt;  &lt;&gt;
        ///&lt;BC&gt;  &lt;Load&gt;  &lt;Bracing&gt;  &lt;N of loads&gt;  &lt;lu_factor&gt;  &lt;dFactor&gt;  &lt;lu_factor&gt; &lt;dFactor&gt;  &lt;lu_factor&gt;  &lt;dFactor&gt;
        ///Cantilever,UniformlyDistributed,Unbraced,1,1.33,0,0.9,3,0.9,3
        ///Cantilever,Concentrated,Unbraced,1,1.87,0,1.44,3,1.44,3
        ///SingleSpan,UniformlyDistributed,Unbraced,1,2.06,0,1.63,3,1.63,3
        ///SingleSpan,Concentrated,Unbraced,1,1.8,0,1.37,3,1.37,3
        ///SingleSpan,Concentrated,Unbraced,2,2.06,0,1.63,3,1.84,0
        ///SingleSpan,Concentrated,BracedAt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table3_3_3Effective_Length {
            get {
                return ResourceManager.GetString("NDS2015_Table3_3_3Effective_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grade&gt;&lt;Depth&gt;&lt;Thickness&gt;&lt;Fb&gt;&lt;Ft&gt;&lt;Fc&gt;
        ///Other,4,3,1.5,1.5,1.15
        ///Other,4,4,1.5,1.5,1.15
        ///Other,5,3,1.4,1.4,1.1
        ///Other,5,4,1.4,1.4,1.1
        ///Other,6,3,1.3,1.3,1.1
        ///Other,6,4,1.3,1.3,1.1
        ///Other,8,3,1.2,1.2,1.05
        ///Other,8,4,1.3,1.2,1.05
        ///Other,10,3,1.1,1.1,1
        ///Other,10,4,1.2,1.1,1
        ///Other,12,3,1,1,1
        ///Other,12,4,1.1,1,1
        ///Other,14,3,0.9,0.9,0.9
        ///Other,14,4,1,0.9,0.9
        ///Stud,4,3,1.1,1.1,1.05
        ///Stud,4,4,1.1,1.1,1.05
        ///Stud,5,3,1,1,1
        ///Stud,5,4,1,1,1
        ///Stud,6,3,1,1,1
        ///Stud,6,4,1,1,1
        ///Stud,8,3,1.2,1.2,1.05
        ///Stud,8,4,1.3,1.2,1.05
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table4A_SizeFactor {
            get {
                return ResourceManager.GetString("NDS2015_Table4A_SizeFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC_16F1_3E16F-1.3E,1600,925,315,195,1.3,0.69,800,315,170,1.1,0.58,675,925,0.41
        ///SC_20F1_5E20F-1.5E,2000,1100,425,195,1.5,0.79,800,315,170,1.2,0.63,725,925,0.41
        ///SC_24F1_7E24F-1.7E,2400,1450,500,210,1.7,0.9,1050,315,185,1.3,0.69,775,1000,0.42
        ///SC_24F1_8E24F-1.8E,2400,1850,650,265,1.8,0.95,1450,560,230,1.6,0.85,1100,1600,0.5
        ///SC_26F1_9E26F-1.9E,2600,1950,650,265,1.9,1,1600,560,230,1.6,0.85,1150,1600,0.5
        ///SC_28F2_1E_SP28F-2.1E SP,2800,2300,805,300,2.1,1.11,1600,650,260,1.7,0.9,1250,1750,0.55
        ///SC_30F2_1E_SP30F- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table5ASimple_DougFir {
            get {
                return ResourceManager.GetString("NDS2015_Table5ASimple_DougFir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC_16F1_3E16F-1.3E,1600,925,315,195,1.3,0.69,800,315,170,1.1,0.58,675,925,0.41
        ///SC_20F1_5E20F-1.5E,2000,1100,425,195,1.5,0.79,800,315,170,1.2,0.63,725,925,0.41
        ///SC_24F1_7E24F-1.7E,2400,1450,500,210,1.7,0.9,1050,315,185,1.3,0.69,775,1000,0.42
        ///SC_24F1_8E24F-1.8E,2400,1450,650,265,1.8,0.95,1450,560,230,1.6,0.85,1100,1600,0.5
        ///SC_26F1_9E26F-1.9E,2600,1950,650,265,1.9,1,1600,560,230,1.6,0.85,1150,1600,0.5
        ///SC_28F2_1E_SP28F-2.1E SP,2800,2300,805,300,2.1,1.11,1600,650,260,1.7,0.9,1250,1750,0.55
        ///SC_30F2_1E_SP30F- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table5ASimple_Other {
            get {
                return ResourceManager.GetString("NDS2015_Table5ASimple_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC_16F1_3E16F-1.3E,1600,925,315,195,1.3,0.69,800,315,170,1.1,0.58,675,925,0.41
        ///SC_20F1_5E20F-1.5E,2000,1100,425,195,1.5,0.79,800,315,170,1.2,0.63,725,925,0.41
        ///SC_24F1_7E24F-1.7E,2400,1450,500,210,1.7,0.9,1050,315,185,1.3,0.69,775,1000,0.42
        ///SC_24F1_8E24F-1.8E,2400,1950,650,300,1.8,0.95,1450,560,260,1.6,0.85,1100,1600,0.55
        ///SC_26F1_9E26F-1.9E,2600,1950,650,300,1.9,1,1600,560,260,1.6,0.85,1150,1600,0.55
        ///SC_28F2_1E_SP28F-2.1E SP,2800,2300,805,300,2.1,1.11,1600,650,260,1.7,0.9,1250,1750,0.55
        ///SC_30F2_1E_SP30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table5ASimple_SP_NoWane {
            get {
                return ResourceManager.GetString("NDS2015_Table5ASimple_SP_NoWane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC_16F1_3E16F-1.3E,1600,925,315,195,1.3,0.69,800,315,170,1.1,0.58,675,925,0.41
        ///SC_20F1_5E20F-1.5E,2000,1100,425,161.85,1.5,0.79,800,315,170,1.2,0.63,725,925,0.41
        ///SC_24F1_7E24F-1.7E,2400,1450,500,174.3,1.7,0.9,1050,315,185,1.3,0.69,775,1000,0.42
        ///SC_24F1_8E24F-1.8E,2400,1950,650,300,1.8,0.95,1450,560,260,1.6,0.85,1100,1600,0.55
        ///SC_26F1_9E26F-1.9E,2600,1950,650,300,1.9,1,1600,560,260,1.6,0.85,1150,1600,0.55
        ///SC_28F2_1E_SP28F-2.1E SP,2800,2300,805,300,2.1,1.11,1600,650,260,1.7,0.9,1250,1750,0.55
        ///SC_30F2_1E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table5ASimple_SP_Wane1s {
            get {
                return ResourceManager.GetString("NDS2015_Table5ASimple_SP_Wane1s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC_16F1_3E16F-1.3E,1600,925,315,195,1.3,0.69,800,315,170,1.1,0.58,675,925,0.41
        ///SC_20F1_5E20F-1.5E,2000,1100,425,130.65,1.5,0.79,800,315,170,1.2,0.63,725,925,0.41
        ///SC_24F1_7E24F-1.7E,2400,1450,500,140.7,1.7,0.9,1050,315,185,1.3,0.69,775,1000,0.42
        ///SC_24F1_8E24F-1.8E,2400,1950,650,300,1.8,0.95,1450,560,260,1.6,0.85,1100,1600,0.55
        ///SC_26F1_9E26F-1.9E,2600,1950,650,300,1.9,1,1600,560,260,1.6,0.85,1150,1600,0.55
        ///SC_28F2_1E_SP28F-2.1E SP,2800,2300,805,300,2.1,1.11,1600,650,260,1.7,0.9,1250,1750,0.55
        ///SC_30F2_1E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NDS2015_Table5ASimple_SP_Wane2s {
            get {
                return ResourceManager.GetString("NDS2015_Table5ASimple_SP_Wane2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoodStructuralPanel,Structural_I,5/16,1-1/4,6d,400,13,10,600,18,13,780,23,16,1020,35,22,560,840,1090,1430
        ///WoodStructuralPanel,Structural_I,3/8,1-3/8,8d,460,19,14,720,24,17,920,30,20,1220,43,24,645,1010,1290,1710
        ///WoodStructuralPanel,Structural_I,7/16,1-3/8,8d,510,16,13,790,21,16,1010,27,19,1340,40,24,715,1105,1415,1875
        ///WoodStructuralPanel,Structural_I,15/32,1-3/8,8d,560,14,11,860,18,14,1100,24,17,1460,37,23,785,1205,1540,2045
        ///WoodStructuralPanel,Structural_I,15/32,1-1/2,10d,680,22,16,1020,29,20,1330,36,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDPWS2015Table4_3A {
            get {
                return ResourceManager.GetString("SDPWS2015Table4_3A", resourceCulture);
            }
        }
    }
}
