//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodestruct.Concrete.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodestruct.Concrete.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation|Diameter|Area|Weight
        ///3,0.375,0.11,0.376
        ///4,0.5,0.2,0.668
        ///5,0.625,0.31,1.043
        ///6,0.75,0.44,1.502
        ///7,0.875,0.6,2.044
        ///8,1,0.79,2.67
        ///9,1.128,1,3.4
        ///10,1.27,1.27,4.303
        ///11,1.41,1.56,5.313
        ///14,1.693,2.25,7.65
        ///18,2.257,4,13.6
        ///.
        /// </summary>
        internal static string ACI_MildRebarProperties {
            get {
                return ResourceManager.GetString("ACI_MildRebarProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NP-CIP-SLAB OR JOIST-CastAgainstEarth,All,All,3,3,3
        ///NP-CIP-SLAB OR JOIST-ExposedToWeather,5,5,1.5,2,2
        ///NP-CIP-SLAB OR JOIST-Protected,11,11,0.75,1.5,1.5
        ///NP-CIP-WALL-CastAgainstEarth,All,All,3,3,3
        ///NP-CIP-WALL-ExposedToWeather,5,5,1.5,2,2
        ///NP-CIP-WALL-Protected,11,11,0.75,1.5,1.5
        ///NP-CIP-BEAM-CastAgainstEarth,All,All,3,3,3
        ///NP-CIP-BEAM-ExposedToWeather,5,5,1.5,2,2
        ///NP-CIP-BEAM-Protected,All,All,1.5,1.5,1.5
        ///NP-CIP-COLUMN OR PEDESTAL-CastAgainstEarth,All,All,3,3,3
        ///NP-CIP-COLUMN OR PEDESTAL-ExposedToWeather [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACI_RebarCover {
            get {
                return ResourceManager.GetString("ACI_RebarCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.25,0.049,0.032
        ///0.375,0.11,0.078
        ///0.5,0.196,0.142
        ///0.625,0.307,0.226
        ///0.75,0.442,0.334
        ///0.875,0.601,0.462
        ///1,0.785,0.606
        ///1.125,0.994,0.763
        ///1.25,1.227,0.969
        ///1.375,1.485,1.16
        ///1.5,1.767,1.41
        ///1.75,2.405,1.9
        ///2,3.142,2.5
        ///.
        /// </summary>
        internal static string AnchorAreas {
            get {
                return ResourceManager.GetString("AnchorAreas", resourceCulture);
            }
        }
    }
}
