//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodestruct.Loads.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodestruct.Loads.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1_1,100
        ///C1_2,105
        ///C1_3,VAR
        ///C2_1,110
        ///C2_2,115
        ///C2_3,VAR
        ///C3_1,115
        ///C3_2,120
        ///C3_3,VAR
        ///.
        /// </summary>
        internal static string ASCE7_10F26_5_1WindZones {
            get {
                return ResourceManager.GetString("ASCE7_10F26_5_1WindZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWFRS,Main Wind Force Resisting System (MWFRS),0.85
        ///CC,Components and Cladding,0.85
        ///ArchRoof,Arched roof,0.85
        ///ChimneySquare,Chimney, tank, or similar (Square),0.9
        ///ChimneyHex,Chimney, tank, or similar (Hexagonal),0.95
        ///ChimneyRound,Chimney, tank, or similar (Round),0.95
        ///FreestandingWall,Freestanding wall,0.85
        ///FreestandingSign,Freestanding sign,0.85
        ///AttachedSign,Attached sign,0.85
        ///Lattice,Lattice framework,0.85
        ///OpenSign,Open sign,0.85
        ///TrussedTower,Trussed tower (Triangular, square, rectangular),0.85 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCE7_10F26_6_1Kd {
            get {
                return ResourceManager.GetString("ASCE7_10F26_6_1Kd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoDimensionalRidge,3
        ///TwoDimensionalEscarpment,2.5
        ///ThreeDimensionalAxisymHill,4
        ///.
        /// </summary>
        internal static string ASCE7_10F26_8_1Gamma {
            get {
                return ResourceManager.GetString("ASCE7_10F26_8_1Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoDimensionalRidge,B,1.3
        ///TwoDimensionalEscarpment,B,0.75
        ///ThreeDimensionalAxisymHill,B,0.95
        ///TwoDimensionalRidge,C,1.45
        ///TwoDimensionalEscarpment,C,0.85
        ///ThreeDimensionalAxisymHill,C,1.05
        ///TwoDimensionalRidge,D,1.55
        ///TwoDimensionalEscarpment,D,0.95
        ///ThreeDimensionalAxisymHill,D,1.15
        ///.
        /// </summary>
        internal static string ASCE7_10F26_8_1K1OverHToLh {
            get {
                return ResourceManager.GetString("ASCE7_10F26_8_1K1OverHToLh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoDimensionalRidge,UpwindOfCrest,1.5
        ///TwoDimensionalEscarpment,UpwindOfCrest,1.5
        ///ThreeDimensionalAxisymHill,UpwindOfCrest,1.5
        ///TwoDimensionalRidge,DownwindOfCrest,1.5
        ///TwoDimensionalEscarpment,DownwindOfCrest,4
        ///ThreeDimensionalAxisymHill,DownwindOfCrest,1.5
        ///.
        /// </summary>
        internal static string ASCE7_10F26_8_1Mu {
            get {
                return ResourceManager.GetString("ASCE7_10F26_8_1Mu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.05,0.1,0.2,0.5,1,2,4,5,10,20,30,45
        ///0.16,1.95,1.9,1.85,1.85,1.8,1.8,1.85,1.85,1.85,1.9,1.9,1.95
        ///0.2,1.95,1.9,1.85,1.8,1.8,1.8,1.8,1.8,1.85,1.9,1.9,1.95
        ///0.3,1.95,1.9,1.85,1.8,1.8,1.8,1.8,1.8,1.8,1.85,1.85,1.85
        ///0.5,1.95,1.85,1.8,1.75,1.75,1.7,1.7,1.7,1.7,1.7,1.7,1.75
        ///0.7,1.9,1.85,1.75,1.7,1.65,1.6,1.6,1.55,1.55,1.55,1.55,1.55
        ///0.9,1.85,1.75,1.7,1.6,1.55,1.5,1.45,1.45,1.4,1.4,1.4,1.4
        ///1,1.8,1.7,1.65,1.55,1.45,1.4,1.35,1.35,1.3,1.3,1.3,1.3
        ///.
        /// </summary>
        internal static string ASCE7_10Figure29_4_1SignsCaseAB {
            get {
                return ResourceManager.GetString("ASCE7_10Figure29_4_1SignsCaseAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,3,4,5,6,7,8,9,10,11,12,13,45
        ///1,2.25,2.6,2.9,3.1r,3.3r,3.4r,3.55r,3.65r,3.75r,3.83333333333333r,3.91666666666667r,4r,4.3r
        ///2,1.5,1.7,1.9,2,2.15,2.25,2.3,2.35,2.45,2.5,2.55,2.6,2.55
        ///3,-1,1.15,1.3,1.45,1.55,1.65,1.7,1.75,1.85,1.9,1.95,2,1.95
        ///4,-1,-1,1.2714,1.3929,1.4786,1.5643,1.6071,1.6429,1.7214,1.647619048,1.573809524,1.5,1.85
        ///5,-1,-1,1.2429,1.3357,1.4071,1.4786,1.5143,1.5357,1.5929,1.511904762,1.430952381,1.35,1.85
        ///6,-1,-1,1.2143,1.2786,1.3357,1.3929,1.4214,1.4286,1.4643,1.396190476,1.328095238,1.26 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCE7_10Figure29_4_1SignsCaseC {
            get {
                return ResourceManager.GetString("ASCE7_10Figure29_4_1SignsCaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential building,Residential building,II
        ///Commercial building,Commercial building,II
        ///Industrial building,Industrial building,II
        ///Theater or hall,Theater or hall,III
        ///Assembly use,Assembly use,III
        ///Elementary school,Elementary school,III
        ///Prison,Prison,III
        ///Small healthcare facility,Small healthcare facility,III
        ///Power generating station,Power generating station,III
        ///Water treatment plant,Water treatment plant,III
        ///Sewage treatment plant,Sewage treatment plant,III
        ///Telecommunication center,Major telecom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCE7_10T1_5_1RiskCategories {
            get {
                return ResourceManager.GetString("ASCE7_10T1_5_1RiskCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCE7-10Table11.4-2
        ///
        ///0.25,A,1.0,Fa
        ///0.25,B,1.0,Fa
        ///0.25,C,1.2,Fa
        ///0.25,D,1.6,Fa
        ///0.25,E,2.5,Fa
        ///0.25,F,0.0,Fa
        ///
        ///0.5,A,0.8,Fa
        ///0.5,B,1.0,Fa
        ///0.5,C,1.2,Fa
        ///0.5,D,1.4,Fa
        ///0.5,E,1.7,Fa
        ///0.5,F,0.0,Fa
        ///
        ///0.75,A,0.8,Fa
        ///0.75,B,1.0,Fa
        ///0.75,C,1.1,Fa
        ///0.75,D,1.2,Fa
        ///0.75,E,1.2,Fa
        ///0.75,F,0.0,Fa
        ///
        ///1.0,A,0.8,Fa
        ///1.0,B,1.0,Fa
        ///1.0,C,1.0,Fa
        ///1.0,D,1.1,Fa
        ///1.0,E,0.9,Fa
        ///1.0,F,0.0,Fa
        ///
        ///1.25,A,0.8,Fa
        ///1.25,B,1.0,Fa
        ///1.25,C,1.0,Fa
        ///1.25,D,1.0,Fa
        ///1.25,E,0.9,Fa
        ///1.25,F,0.0,Fa
        ///
        ///ASCE7-10Table11.4-2
        ///
        ///0.1,A,0.8,Fv
        ///0.1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCE7_10T11_4_1AND2 {
            get {
                return ResourceManager.GetString("ASCE7_10T11_4_1AND2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. BEARING WALL SYSTEMS,,,,,,,,,,,
        ///A1, Special reinforced concrete shear walls,14.2,5,2.5,5,NL ,NL ,160,160,100,lm
        ///A2, Ordinary reinforced concrete shear walls,14.2,4,2.5,4,NL ,NL ,NP ,NP ,NP ,l
        ///A3, Detailed plain concrete shear walls,14.2,2,2.5,2,NL ,NP ,NP ,NP ,NP ,l
        ///A4, Ordinary plain concrete shear walls,14.2,1.5,2.5,1.5,NL ,NP ,NP ,NP ,NP ,l
        ///A5, Intermediate precast shear walls,14.2,4,2.5,4,NL ,NL ,40k ,40k ,40k ,l
        ///A6, Ordinary precast shear walls,14.2,3,2.5,3,NL ,NP ,NP ,NP ,NP ,l
        ///A7, Special r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCE7_10T12_2_1 {
            get {
                return ResourceManager.GetString("ASCE7_10T12_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.4,1.4
        ///0.3,1.4
        ///0.2,1.5
        ///0.15,1.6
        ///0.1,1.7
        ///.
        /// </summary>
        internal static string ASCE7_10T12_8_1 {
            get {
                return ResourceManager.GetString("ASCE7_10T12_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteelMomentResistingFrame,0.028,0.8
        ///ConcreteMomentResistingFrame,0.016,0.9
        ///SteelEccentricallyBracedFrame,0.03,0.75
        ///SteelBucklingRestrainedBracedFrame,0.03,0.75
        ///OtherStructuralSystem,0.02,0.75
        ///.
        /// </summary>
        internal static string ASCE7_10T12_8_2 {
            get {
                return ResourceManager.GetString("ASCE7_10T12_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B,7,1200,0.25,0.45,0.3,320,0.333333333,30
        ///C,9.5,900,0.153846154,0.65,0.2,500,0.2,15
        ///D,11.5,700,0.111111111,0.8,0.15,650,0.125,7
        ///.
        /// </summary>
        internal static string ASCE7_10T26_9_1 {
            get {
                return ResourceManager.GetString("ASCE7_10T26_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly fixed seats,Assembly area or theater with fixed seats (fastened to floor),60,NP,
        ///Assembly with movable seats,Assembly area or theater lobby,100,NP,
        ///Assembly lobby,Assembly area or theater with movable seats,100,NP,
        ///Assembly platform,Assembly area or theater platform,100,NP,
        ///Stage floor,Assembly area or theater stage floor,150,NP,
        ///Dining,Dining room or restaurant,100,NP,
        ///
        ///Bowling alley,Bowling alley, poolroom, or similar,75,NP,
        ///Ballroom,Dance hall or ballroom,100,NP,
        ///Gym,Gym,100,NP,
        ///Bleach [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCE7_10T4_1LiveLoads {
            get {
                return ResourceManager.GetString("ASCE7_10T4_1LiveLoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B,FullyExposed,0.9
        ///C,FullyExposed,0.9
        ///D,FullyExposed,0.8
        ///AboveTreelineMountain,FullyExposed,0.7
        ///B,PartiallyExposed,1
        ///C,PartiallyExposed,1
        ///D,PartiallyExposed,0.9
        ///AboveTreelineMountain,PartiallyExposed,0.8
        ///B,Sheltered,1.2
        ///C,Sheltered,1.1
        ///D,Sheltered,1
        ///AboveTreelineMountain,Sheltered,-1
        ///.
        /// </summary>
        internal static string ASCE7_10T7_2SnowCe {
            get {
                return ResourceManager.GetString("ASCE7_10T7_2SnowCe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C01,1.1,Regular structure
        ///C02,1.1,Structure kept just above freezing
        ///C03,1.3,Structure  kept below freezing
        ///C04,0.85,Continuously heated greenhouse
        ///C05,1.2,Open structure
        ///C06,1.2,Unheated structure
        ///C07,1.1,Structure having  cold ventilated roof
        ///.
        /// </summary>
        internal static string ASCE7_10T7_3SnowCt {
            get {
                return ResourceManager.GetString("ASCE7_10T7_3SnowCt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4,39
        ///8,79
        ///12,115
        ///16,155
        ///.
        /// </summary>
        internal static string DeadLoadClayBrick {
            get {
                return ResourceManager.GetString("DeadLoadClayBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BlockGroutingType&gt; &lt;Density&gt; &lt;Grout spacing&gt; &lt;4 in. block&gt; &lt;6 in. block&gt; &lt;8 in. block&gt; &lt;10 in. block&gt; &lt;12 in. block&gt;
        ///Hollow,105 pcf,0,22,24,31,37,43
        ///Hollow,125 pcf,0,26,28,36,44,50
        ///Hollow,135 pcf,0,29,30,39,47,54
        ///FullGrout,105 pcf,0,,55,75,95,115
        ///FullGrout,125 pcf,0,,59,81,102,123
        ///FullGrout,135 pcf,0,,62,83,105,127
        ///PartialGrout,105 pcf,48,,29,38,47,55
        ///PartialGrout,105 pcf,40,,30,40,49,57
        ///PartialGrout,105 pcf,32,,32,42,52,61
        ///PartialGrout,105 pcf,24,,34,46,57,67
        ///PartialGrout,105 pcf,16,,40,53,66,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeadLoadCMU {
            get {
                return ResourceManager.GetString("DeadLoadCMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d1_5,p1.5x6,Gage22,2
        ///d1_5,p1.5x6,Gage20,2.4
        ///d1_5,p1.5x6,Gage 18,3
        ///d1_5,p1.5x6,Gage16,3.6
        ///d2,p2x12,Gage22,1.8
        ///d2,p2x12,Gage20,2.2
        ///d2,p2x12,Gage 18,2.8
        ///d2,p2x12,Gage16,3.4
        ///d3,p3x12,Gage22,2
        ///d3,p3x12,Gage20,2.4
        ///d3,p3x12,Gage 18,3
        ///d3,p3x12,Gage16,3.6
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string DeadLoadCompositeDeckOnly {
            get {
                return ResourceManager.GetString("DeadLoadCompositeDeckOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d1_5,3.5,p1_5x6,33,26
        ///d1_5,4,p1_5x6,39,30
        ///d1_5,4.5,p1_5x6,45,35
        ///d1_5,5,p1_5x6,51,39
        ///d1_5,5.5,p1_5x6,57,44
        ///d1_5,6,p1_5x6,63,49
        ///d1_5,3.5,p1_5x6INV,38,29
        ///d1_5,4,p1_5x6INV,44,34
        ///d1_5,4.5,p1_5x6INV,50,38
        ///d1_5,5,p1_5x6INV,56,43
        ///d1_5,5.5,p1_5x6INV,62,47
        ///d1_5,6,p1_5x6INV,68,52
        ///d2,4,p2x12,39,30
        ///d2,4.5,p2x12,45,35
        ///d2,5,p2x12,51,40
        ///d2,5.5,p2x12,57,44
        ///d2,6,p2x12,63,51
        ///d2,6.5,p2x12,69,53
        ///d3,5,p3x12,44,34
        ///d3,5.5,p3x12,50,39
        ///d3,6,p3x12,57,43.6
        ///d3,6.5,p3x12,63,48
        ///d3,7,p3x12,69,55
        ///d3,7.5,p3x12,75,58
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeadLoadDeckWithConcrete {
            get {
                return ResourceManager.GetString("DeadLoadDeckWithConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d120pcf,1/2-in. Backing,Backing1_2,5
        ///d120pcf,5/8-in. Backing,Backing5_8,6.3
        ///d120pcf,3/8-in. Exposed Aggregate Face,ExposedAggregate3_8,3.8
        ///d140pcf,1/2-in. Backing,Backing1_2,5.8
        ///d140pcf,5/8-in. Backing,Backing5_8,7.3
        ///d140pcf,3/8-in. Exposed Aggregate Face,ExposedAggregate3_8,4.4
        ///.
        /// </summary>
        internal static string DeadLoadGFRC {
            get {
                return ResourceManager.GetString("DeadLoadGFRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d1_5,B,1.5&quot; Type B-Wide Rib ,Gage22,2
        ///d1_5,B,1.5&quot; Type B-Wide Rib ,Gage20,2.4
        ///d1_5,B,1.5&quot; Type B-Wide Rib ,Gage18,3
        ///d1_5,B,1.5&quot; Type B-Wide Rib ,Gage16,3.6
        ///d1_5,F,1.5&quot; Type F-Intermediate Rib ,Gage22,1.8
        ///d1_5,F,1.5&quot; Type F-Intermediate Rib ,Gage20,2.2
        ///d1_5,F,1.5&quot; Type F-Intermediate Rib ,Gage18,2.8
        ///d1_5,A,1.5&quot; Type A-Narrow Rib ,Gage22,1.8
        ///d1_5,A,1.5&quot; Type A-Narrow Rib ,Gage20,2.2
        ///d1_5,A,1.5&quot; Type A-Narrow Rib ,Gage18,3
        ///d3,N,3&quot; Type N-Deep Rib ,Gage22,2.4
        ///d3,N,3&quot; Type N-Deep Rib ,Gage20,2.8
        ///d3,N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeadLoadRoofDeck {
            get {
                return ResourceManager.GetString("DeadLoadRoofDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ID&gt;  &lt;Description&gt;  &lt;Weight&gt;  &lt;Notes&gt;  &lt;Unit thickness&gt;  &lt;ClassName&gt;  &lt;Reference&gt;
        ///AcousticalFiberBoard,Acoustical fiber board ,1,,,,ASCE7-10 Table C3-1
        ///GypsumBoard,Gypsum board,0.55,(assumed as 0.55 psf per 0.125-in. thickness),0.125,ComponentGeneral,ASCE7-10 Table C3-1
        ///CementBoard,Cement board,0.75,(assumed as 0.75 psf per 0.125-in. thickness),0.125,ComponentGeneral,ASCE7-10 Table C3-1
        ///Plaster,Plaster on tile or concrete ,5,,,,ASCE7-10 Table C3-1
        ///PlasterOnWoodLath,Plaster on wood lath ,8,,,,ASCE7-10  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeadLoadSummaryTable {
            get {
                return ResourceManager.GetString("DeadLoadSummaryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs2X6,at12,2.4,6
        ///cs2X8,at12,3.4,6
        ///cs2X10,at12,4.2,7
        ///cs2X12,at12,5,8
        ///cs2X6,at16,2,5
        ///cs2X8,at16,2.6,6
        ///cs2X10,at16,3.4,6
        ///cs2X12,at16,4,7
        ///cs2X6,at24,1.6,5
        ///cs2X8,at24,2,5
        ///cs2X10,at24,2.6,6
        ///cs2X12,at24,3,6
        ///.
        /// </summary>
        internal static string DeadLoadWoodFraming {
            get {
                return ResourceManager.GetString("DeadLoadWoodFraming", resourceCulture);
            }
        }
    }
}
