//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodestruct.Aluminum.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodestruct.Aluminum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Alloy&gt;&lt;Temper&gt;&lt;ThicknessRange&gt;&lt;Product&gt;&lt;F_tu&gt;&lt;F_ty&gt;&lt;F_tuw&gt;&lt;F_tyw&gt;&lt;k_t&gt;&lt;F_tyw_Alt&gt;
        ///1060,H12,From 0.017 to 2,sheet &amp; plate,11,9,8,2.5,1,2.5
        ///1060,H12,From 0.01 to 0.5,drawn tube,10,4,8.5,2.5,1,2.5
        ///1060,H14,From 0.009 to 1,sheet &amp; plate,12,10,8,2.5,1,2.5
        ///1060,H14,From 0.01 to 0.5,drawn tube,12,10,8.5,2.5,1,2.5
        ///1100,H12,From 0.017 to 2,sheet &amp; plate,14,11,11,3.5,1,3.5
        ///1100,H12,From 0.014 to 0.5,drawn tube,14,11,11,3.5,1,3.5
        ///1100,H14,From 0.009 to 1,sheet &amp; plate,16,14,11,3.5,1,3.5
        ///1100,H14,From 0.014 to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AA2015_TableA3_3WroughtAluminumProducts {
            get {
                return ResourceManager.GetString("AA2015_TableA3_3WroughtAluminumProducts", resourceCulture);
            }
        }
    }
}
