//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodestruct.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodestruct.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W44X335,5.5,38,3
        ///W44X290,5.5,38,2.8125
        ///W44X262,5.5,38,2.625
        ///W44X230,5.5,38,2.4375
        ///W40X655,7.5,34,4.8125
        ///W40X593,7.5,34,4.5
        ///W40X503,7.5,34,4
        ///W40X431,7.5,34,3.625
        ///W40X397,7.5,34,3.5
        ///W40X372,7.5,34,3.3125
        ///W40X362,7.5,34,3.25
        ///W40X324,7.5,34,3.0625
        ///W40X297,7.5,34,2.9375
        ///W40X277,7.5,34,2.875
        ///W40X249,7.5,34,2.6875
        ///W40X215,7.5,34,2.5
        ///W40X199,7.5,34,2.3125
        ///W40X392,7.5,34,3.8125
        ///W40X331,7.5,34,3.375
        ///W40X327,7.5,34,3.375
        ///W40X294,7.5,34,3.1875
        ///W40X278,7.5,34,3.0625
        ///W40X264,7.5,34,3
        ///W40X235,7.5,34 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AISCShapeDatabaseDetailingImperial {
            get {
                return ResourceManager.GetString("AISCShapeDatabaseDetailingImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShapeId,Type,W,A,d,Ht,h,OD,bf,B,b,ID,tw,tf,t,tnom,tdes,kdes,x,y,eo,xp,yp,Ix,Zx,Sx,rx,Iy,Zy,Sy,ry,Iz,rz,Sz,J,Cw,C,Wno,Sw1,Sw2,Sw3,Qf,Qw,ro,H,tanAlpha,Qs,Iw,zA,zB,zC,wA,wB,wC,SwA,SwB,SwC,SzA,SzB,SzC,rts,ho,PA,PB
        ///W44X335,W,335,98.5,44.0,0,0,0,15.9,0,0,0,1.03,1.77,0,0,0,2.56,0,0,0,0,0,31100,1620,1410,17.8,1200,236,150,3.49,0,0,0,74.7,535000,0,168,1180,0,0,278,805,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.24,42.2,132,148
        ///W44X290,W,290,85.4,43.6,0,0,0,15.8,0,0,0,0.865,1.58,0,0,0,2.36,0,0,0,0,0,27000,1410,1240,17.8,10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AISCShapeDatabaseImperial {
            get {
                return ResourceManager.GetString("AISCShapeDatabaseImperial", resourceCulture);
            }
        }
    }
}
